name: cSpell
on:
    pull_request:
    push:
        branches:
            - master

jobs:
    cspell:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npx cspell@latest "**/*"
